---

- hosts: all

  vars_files:
    - config.yaml
    - secrets.yaml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: ctorgalson.oh-my-zsh
      become: true

  tasks:
    - import_tasks: tasks/post-homebrew.yaml
      tags: ['homebrew']
    - import_tasks: tasks/osx.yaml
      when: configure_osx
      tags: ['osx']
